### PR TITLE
Progress

### PR DESCRIPTION
**Pull request by ThreeMonth03**
I write the documents for this repo, including [./README.md](https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library/blob/progress/README.md) and [./python/README.md](https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library/blob/progress/python/README.md)

### CODE REVIEW

**Comment by yungyuc** [comment]
@ThreeMonth03 you should have tagged me here in the PR, not in https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library/pull/3#issuecomment-1859030231

**Comment by yungyuc** [comment]
The documents look reasonable.  But be careful to not copy it in your slides.  Documents pasted in slides work poorly.

**Comment by ThreeMonth03** [comment]
@SUNGOD3 Testing for the tag function.

**Comment by ThreeMonth03** [comment]
> @ThreeMonth03 you should have tagged me here in the PR, not in [#3 (comment)](https://github.com/ThreeMonth03/Conjugate-Gradient-Method-library/pull/3#issuecomment-1859030231)

Sorry,  I misunderstand that only the reviewer or the participant could be tagged in the comment, 
and I know how to tag the people in the new PR right now.
Thank's for your reminding.

**Comment by ThreeMonth03** [comment]
> The documents look reasonable. But be careful to not copy it in your slides. Documents pasted in slides work poorly.

That's right. I will show more detail and image in my slides. Thank you for your suggestion.

**Pull request merged**
